### PR TITLE
this.name undefined error - crashes Homebridge

### PR DESCRIPTION
**Pull request by PatchworkBoy**
Line 354 this.name.indexOf results in undefined on this.name when doing a http get - scope issue?
var name = this.name; at line 322 fixes.

@xTheRamon - better way to do this that I’m missing?

### CODE REVIEW

**Comment by PatchworkBoy** [comment]
PS: you do realise I’m just gonna fire all my ugly code in your direction now to be cleaned up and refactored before committing, don’t you? 😀

**Comment by PatchworkBoy** [comment]
Def need you to take a look at https://github.com/PatchworkBoy/homebridge-eDomoticz/pull/35/commits/7c7a0a842842401d3ef110607f5cf4a00147d725 as can’t work out where the error is coming from...

**Comment by PatchworkBoy** [comment]
Ignore https://github.com/PatchworkBoy/homebridge-eDomoticz/pull/35/commits/88a7aebd8e4e68251e03a7b896f597353fe8d824 and https://github.com/PatchworkBoy/homebridge-eDomoticz/pull/35/commits/e69b700167c42b1330a0e39cbf82edd8fb3533bd - fixed nothing!

**Comment by xTheRamon** [comment]
Whoops. I totally messed up on this one. Fixed it in the `mqtt-integration` branch!

The whole point why I refactored this is that there were double references to `this`.
At some points in code `var that = this;` was used.
At other points `.bind(this)` was used.

Basically `.bind(this)` after a function means that it binds the `this` for that function to the `this` outside of the function. Basically `var that = this` without the word `that`.

I forgot to map `this` to the map functions. So basically `s.mapArray` was mapping stuff to it's own `this`. It never reached the accessory.

Now, if you don't mind, I'll go sit and cry in a corner for some time.

**Comment by PatchworkBoy** [comment]
*snigger*  No worries!

The var that = this stuff leaked over from the ORIGINAL homebridge-domoticz plugin that gizmocuz wrote years back (I had nothing to do with that one)... before Homebridge was rewritten. You can still find it in the Z-wave plugins and a few others. Can't honestly recall why it was needed to start with.

**Pull request closed without merging**
