### PR TITLE
Added support for P1 Smart Meter (Energy) & Oregon UVN800

### PR DESCRIPTION
**Pull request by EddyK69**

### CODE REVIEW

**Comment by PatchworkBoy** [comment]
Not quite as straight forward - the P1 Smart Meter also has Gas subtypes etc that need accounting for. Working on it!

**Comment by EddyK69** [comment]
Fair enough, it seems to work for me now though, see
img_0687

What about the types? I all see the same icons for the types...
img_0685
instead of..
eve-homekit-iphone_w400_h890

And...
How can i ask Siri about the windspeed, rainfall and power consumption? What sentences can i use?

**Comment by PatchworkBoy** [comment]
Yep, it will work for you for your kWh readings, but it won't work for me for instance with my Gas Pulse readings, which also come thru as Type "P1 Smart Meter", SubType "Gas", not SubType "kWh". P1 Smart Meter needs it's own service that accounts for all it's possible subtypes, rather than riding on the "General" type service.

Icon types - those are ElgatoEve specific types - i.e.: as used by Legato's own hardware and thus with their service UUIDs which their app is built to recognise. Custom types by anyone other than Elgato won't get their icon.

And windspeed, rainfall, power etc (anything WITHOUT an icon) - can't communicate with Siri - not part of the HomeKit spec. If not in the HomeKit Spec, Siri will never be able to talk to them.

All as described at https://www.domoticz.com/forum/viewtopic.php?f=36&t=10272&start=100#p74485

**Comment by EddyK69** [comment]
Thanx for your explenations about the type & voice commands. :D 
PR can be closed...

**Comment by PatchworkBoy** [comment]
Will do - full(ish) P1 Smart Meter support _should_ be added this weekend anyways... I'll keep your UVN800 identifiers in there tho...

**Comment by PatchworkBoy** [comment]
v0.1.14 should now support P1 Smart Meter and UVN800... :+1:

**Comment by EddyK69** [comment]
Thnx, but....
I'm missing the P1 Smart Meter subtype 'Energy'... ;)

**Comment by PatchworkBoy** [comment]
Heh - try again - should be there now...

**Pull request closed without merging**
